export const GET_ALL_LOBBIES = '@app/GET_ALL_LOBBIES'
export const GET_ALL_LOBBIES_SUCCESS = '@app/GET_ALL_LOBBIES_SUCCESS'
export const GET_ALL_LOBBIES_FAIL = '@app/GET_ALL_LOBBIES_FAIL'

export const SET_CURRENT_LOBBY = '@app/SET_CURRENT_LOBBY'
export const ADD_LOBBY = '@app/ADD_LOBBY'
export const ADD_PLAYER = '@app/ADD_PLAYER'
export const QUESTION_ANSWERED = '@app/QUESTION_ANSWERED'
export const RESET_PLAYERS = '@app/RESET_PLAYERS'
export const LIFE_LOST = '@app/LIFE_LOST'